### ISSUE TITLE
Progress

### ISSUE THREAD

**Issue by nathanpena** [dostonnabotov/introduction-to-algorithms#3]
what happened with the project of reading this book?  or what is the status of this project? Hope you do it.

**Comment by dostonnabotov** [comment]
@nathanpena Hey, there! I am still reading it (Chapter 3.1). I just couldn't find free time to post the updates. I will continue posting within a few weeks once I am done with university exams.

**Comment by dostonnabotov** [comment]
@nathanpena Hi, there! I am back to posting updates. It has been a while...
